<!--顶部导航-->
<div class="nav-layout w100">
    <div class="navContainer  clearfix">
        <div class="centerTitle">
            <a href="#"><img src="../../images/memberCenter/logo.png"></a>
        </div>
        <ul class="centerNav">
            <li class="active navItem">账号管理</li>
            <li class="navItem">信息管理</li>
            <li class="navItem"><a href="../../Index.html">网站首页</a></li>
        </ul>
    </div>
</div>

<!--顶部导航End-->